# The URL the site will be built for
base_url = "/"

# Site title and description
title = "Your Professional Blog"
description = "A modern, elegant blog showcasing technical expertise and insights"

# Language code for the site
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Generate RSS feed
generate_feeds = true
feed_filenames = ["rss.xml"]

# Taxonomies (categories and tags) - disabled for now
# taxonomies = [
#     {name = "categories", feed = true},
#     {name = "tags", feed = true},
# ]

[markdown]
# Whether to do syntax highlighting
highlight_code = true
highlight_theme = "nord"

# Enable smart punctuation
smart_punctuation = true

# External links open in new tab
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

[extra]
# Site author information
author = "Your Name"
author_email = "your.email@example.com"
author_bio = "Full-stack developer passionate about modern web technologies, Rust, and creating elegant solutions to complex problems."

# Social media links
social_links = [
    {name = "GitHub", url = "https://github.com/yourusername", icon = "github"},
    {name = "LinkedIn", url = "https://linkedin.com/in/yourprofile", icon = "linkedin"},
    {name = "Twitter", url = "https://twitter.com/yourusername", icon = "twitter"},
    {name = "Email", url = "mailto:your.email@example.com", icon = "email"},
]

# Navigation menu
menu = [
    {name = "Home", url = "/", weight = 1},
    {name = "Blog", url = "/blog/", weight = 2},
    {name = "About", url = "/about/", weight = 3},
    {name = "Contact", url = "/contact/", weight = 4},
]

# SEO and analytics
google_analytics = ""
google_site_verification = ""

# Theme settings
theme_color = "#2563eb"
accent_color = "#3b82f6"

# Enable dark mode toggle
enable_dark_mode = true

# Footer text
footer_text = "Built with ❤️ using Zola and modern web technologies"
